FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /usr/src/app

# Copy application code
COPY ./setup.py ./setup.py
COPY ./docker_kb ./docker_kb  
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt --timeout=300

# copy src code
COPY ./src ./src


RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 4000

# start the server
CMD ["uvicorn", "src.__main__:app", "--host", "0.0.0.0", "--port", "4000", "--proxy-headers"]