# Start from a Miniconda base image
FROM continuumio/miniconda3
# FROM python:3.12-slim

# ENV PORT=8080

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    echo \
    sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN sudo apt-get install apt-transport-https ca-certificates gnupg curl
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-cli -y

# Update conda and install dependencies
RUN conda update conda -y
RUN conda install -n base conda-libmamba-solver -y
RUN conda config --set solver libmamba

# Install required Python libraries
RUN conda install pydantic uvicorn -c conda-forge -y
RUN conda install pytorch torchvision cpuonly -c pytorch -y
RUN conda install -c conda-forge fastapi -y

# Set working directory
WORKDIR /app

# Copy application code
COPY ./setup.py /app/setup.py
COPY ./docker_kb /app/docker_kb  
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt --timeout=300

# Copy the main API file
COPY ./api/__main__.py api.py

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "$PORT"]