version: '3.8'

services:
  docker_basics_rag_gcp:
    env_file: .env
    image: docker_basics_rag_gcp:${DOCKER_BASICS_RAG_VER}
    build:
      context: ../../
      dockerfile: ./api/gcp/dockerfile
    environment:
      API_KEY: 2nn1vqvgifrwP8RjsvyLXmTy4dmtTYE3
      DATA_PATH: /app/database
    volumes:
      - /mnt/data/docker_docs:/app/database:ro #NOTE change "/mnt/data/docker_docs" to your local data location (./docs)
