version: '3.8'

services:
  docker_basics_rag:
    env_file: ./.env
    image: docker_basics_rag:${DOCKER_BASICS_RAG_VER}
    build:
      context: ../
      dockerfile: ./api/dockerfile
    environment:
      API_KEY: 2nn1vqvgifrwP8RjsvyLXmTy4dmtTYE3
      DATA_PATH: /app/database
    volumes:
      - /mnt/data/docker_docs:/app/database:ro
    ports:
      - 5315:8000
